"""add device family

Revision ID: 39484261c920
Revises: 21cf964e4d7c
Create Date: 2026-09-27 11:51:51.287535
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "39484261c920"
down_revision: str | None = "21cf964e4d7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "device_family",
            sa.String(length=32),
            server_default=sa.text("'simulation'"),
            nullable=False,
        ),
    )
    op.create_index("ix_devices_family", "devices", ["device_family"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_devices_family", table_name="devices")
    op.drop_column("devices", "device_family")
    # ### end Alembic commands ###
