"""sensor readings

Revision ID: a27bf23d9b81
Revises: df658a6079ca
Create Date: 2026-10-05 17:18:18.050383
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a27bf23d9b81"
down_revision: str | None = "df658a6079ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name="fk_sensor_readings_device_id_devices",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sensor_readings_device_recorded_at",
        "sensor_readings",
        ["device_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.add_column(
        "devices",
        sa.Column(
            "sampling_interval_seconds", sa.Integer(), server_default=sa.text("300"), nullable=False
        ),
    )
    op.add_column(
        "devices",
        sa.Column("tracking_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.execute(
        """
        UPDATE devices
        SET sampling_interval_seconds =
            CASE
                WHEN jsonb_typeof(default_config -> 'sampling_interval_seconds') = 'number'
                 AND (default_config ->> 'sampling_interval_seconds')::numeric >= 5
                THEN (default_config ->> 'sampling_interval_seconds')::integer
                ELSE 300
            END
        """
    )
    op.create_check_constraint(
        "ck_devices_sampling_interval_min",
        "devices",
        "sampling_interval_seconds >= 5",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_devices_sampling_interval_min", "devices", type_="check")
    op.drop_column("devices", "tracking_enabled")
    op.drop_column("devices", "sampling_interval_seconds")
    op.drop_index("ix_sensor_readings_device_recorded_at", table_name="sensor_readings")
    op.drop_table("sensor_readings")
    # ### end Alembic commands ###
